FROM ubuntu:noble

# ------------------------------------------------------------------------------

ARG DEBIAN_FRONTEND noninteractive

RUN apt-get update; \
    apt upgrade --assume-yes --new-pkgs; \
    apt autoremove --assume-yes --purge; \
    apt clean;

RUN apt-get install --assume-yes \
    build-essential \
    ccache \
    cmake \
    curl \
    g++ \
    git \
    html-xml-utils \
    nano \
    python3 \
    python3-dev \
    python3-pip \
    qt5-qmake \
    qtbase5-dev \
    qtbase5-dev-tools \
    qtchooser \
    vim \
    ;

RUN pip3 install --upgrade --break-system-packages \
    cppyy \
    ;

# ------------------------------------------------------------------------------

USER ubuntu

WORKDIR /home/ubuntu

# ------------------------------------------------------------------------------

COPY --chown=ubuntu:ubuntu --from=ssh ./ ./.ssh/

# ------------------------------------------------------------------------------

# ARG NS3_REPO_URL "git@gitlab.com:nsnam/ns-3-dev.git"
# ARG NS3_REPO_URL "git@gitlab.com:labcomu1/ns-3-dev.git"
ARG NS3_REPO_URL="ssh://git@projetos.imd.ufrn.br:4422/labcomu/ns-3-dev.git"

RUN git clone ${NS3_REPO_URL};

# ------------------------------------------------------------------------------

RUN cd ns-3-dev; \
    ./ns3 configure --enable-examples --enable-tests --build-profile=debug --out=build/debug; \
    ./ns3 build


# ------------------------------------------------------------------------------

# ARG NS3_REPO_BRANCH="master"
ARG NS3_REPO_BRANCH="feature/ftgo-test"

RUN cd ns-3-dev; \
    git pull --all; \
    git checkout ${NS3_REPO_BRANCH};

# ------------------------------------------------------------------------------

RUN cd ns-3-dev; \
    ./ns3 configure --enable-examples --enable-tests --build-profile=debug --out=build/debug; \
    ./ns3 build

# ------------------------------------------------------------------------------

RUN ln --symbolic /share .

# ------------------------------------------------------------------------------
