FROM ubuntu:noble

# ------------------------------------------------------------------------------

ARG DEBIAN_FRONTEND noninteractive

RUN apt-get update; \
    apt upgrade --assume-yes --new-pkgs; \
    apt autoremove --assume-yes --purge; \
    apt clean;

RUN apt-get install --assume-yes \
    build-essential \
    ccache \
    cmake \
    curl \
    g++ \
    git \
    html-xml-utils \
    nano \
    python3 \
    python3-dev \
    python3-pip \
    qt5-qmake \
    qtbase5-dev \
    qtbase5-dev-tools \
    qtchooser \
    vim \
    ;

RUN pip3 install --upgrade --break-system-packages \
    cppyy \
    ;

# ------------------------------------------------------------------------------

USER ubuntu

WORKDIR /home/ubuntu

# ------------------------------------------------------------------------------

RUN ln --symbolic /share .

# ------------------------------------------------------------------------------

RUN git clone https://gitlab.com/labcomu1/ns-3-dev.git;

# ------------------------------------------------------------------------------

RUN cd ns-3-dev; \
    ./ns3 configure --enable-examples --enable-tests --build-profile=debug --out=build/debug; \
    ./ns3 build

# ------------------------------------------------------------------------------
    