services:

  ns3:
    image: ns3
    container_name: ns3
    hostname: ns3
    user: ubuntu:ubuntu
    tty: true
    build:
      dockerfile: Dockerfile.yml
      additional_contexts:
        - ssh=~/.ssh
    volumes:
      - ./share:/share:rw
    networks:
      - ns3

networks:
  ns3:
    driver: bridge

volumes:
  ns3:
    driver: local
